on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: pnpm install --frozen-lockfile
      - run: |
          VERSION=$(jq -r .version <package.json)
          if [[ "$VERSION" = *"-rc."* ]]; then
            pnpm publish --access public --tag rc --no-git-checks
          else
            LATEST_VERSION="$(gh release view --json tagName -q '.tagName' --repo ${{ github.repository }})"
            if [[ "v$VERSION" = "$LATEST_VERSION" ]]; then
              pnpm publish --access public --no-git-checks
            else
              MAJOR="$(awk -F '.' '{ print $1 }' <<< "$VERSION")"
              pnpm publish --access public --tag "v$MAJOR" --no-git-checks
            fi
          fi
