on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile
      - run: |
          VERSION=$(jq -r .version <package.json)
          if [[ "$VERSION" = *"-rc."* ]]; then
            pnpm publish --access public --tag rc --no-git-checks
          else
            LATEST_VERSION="$(gh release view --json tagName -q '.tagName' --repo "$GH_REPOSITORY")"
            if [[ "v$VERSION" = "$LATEST_VERSION" ]]; then
              pnpm publish --access public --no-git-checks
            else
              MAJOR="$(awk -F '.' '{ print $1 }' <<< "$VERSION")"
              pnpm publish --access public --tag "v$MAJOR" --no-git-checks
            fi
          fi
        env:
          GH_REPOSITORY: ${{ github.repository }}
